FROM node:18-alpine3.18 as build
RUN mkdir -p /opt/app
WORKDIR /opt/app
COPY ./ .
RUN npm install
RUN npm run build

# stage 2
FROM nginx:alpine
COPY --from=build /opt/app/dist/frontend/browser /usr/share/nginx/html
COPY ./nginx-custom.conf  /etc/nginx/conf.d/default.conf
CMD sed -i "s,API_URL_LINK_HERE,$API_URL,g" /usr/share/nginx/html/*.js && exec nginx -g 'daemon off;'